### ISSUE TITLE
能不能获取链的基本信息呢

### ISSUE THREAD

**Issue by dwusiq** [ecsoya/fabric-demo#3]
你好，有几个问题想请教下的：
1、有没有接口或者service可以获取一些链的基本信息呢？比如:机构名称、机构下有哪些节点、节点名称等等
2、能不能根据节点名称获取关于节点的一些数据呢？比如：当前块高、节点状态

**Comment by ecsoya** [comment]
IFabricInfoService.queryFabricLedger()

**Comment by dwusiq** [comment]
但这个接口没有节点的名称、块高，而且这些数据是读了本地配置而不是从链上获取的

**Comment by ecsoya** [comment]
FabricLedger中的height就是当前区块的高度，currentHash是最新的区块头Hash。

至于你说的其它信息，都是在创建Fabric网络时就有的信息，SDK中也没有办法读取。

你可以看看HFClient、Channel和NetworkConfig的源码，去寻找一下……

**Comment by dwusiq** [comment]
好的，谢谢

**Comment by dwusiq** [comment]
好的，谢谢
