### ISSUE TITLE
这个实例能支持Fabric2.x吗

### ISSUE THREAD

**Issue by lxj08193** [ecsoya/fabric-demo#9]
这个是我在网上找的最好的入门实例，但是现在有个问题，我不知道如何选择1.x或者2.x

**Comment by cayden** [comment]
> 这个是我在网上找的最好的入门实例，但是现在有个问题，我不知道如何选择1.x或者2.x

你好，你那边运行起来了吗？

**Comment by lxj08193** [comment]
> > 这个是我在网上找的最好的入门实例，但是现在有个问题，我不知道如何选择1.x或者2.x
> 
> 你好，你那边运行起来了吗？

可以运行，只是要安装common.go合约  QQ:867424981

**Comment by Fshenye** [comment]
是还不支持2.x么，我看源码里面 fabric-gateway-java 是 1.4 的

**Comment by ecsoya** [comment]
现在支持2.x了
